name: Deploy to test server

on:
    push:
      branches: [ dev ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Send files to server
            run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
              chmod 600 private_key
              scp -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r app/* ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/app/

          - name: Execute script
            run: |
              ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
                cd /home/github-runner/app
                docker stop aboba_name
                make build
                make run
              EOF
               
